version: '3'
services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7000:7000"
    networks:
      - nodenetwork
    depends_on:
      - mongo
  mongo:
    image: "mongo:latest"
    networks:
      - nodenetwork
    ports:
      - "8000:27017"
networks:
  nodenetwork:
    driver: bridge
